# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16qhFYIfrIKowB5Dc_DYctYySBVxaa26M
"""

# ============================================================
# Claim Status Prediction: Paid vs Denied
# Nested CV + Multiple Models + SHAP
# ============================================================

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

from pathlib import Path

from sklearn.model_selection import StratifiedKFold, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.metrics import (
    roc_auc_score, accuracy_score, precision_score,
    recall_score, f1_score, confusion_matrix
)

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

from xgboost import XGBClassifier
import shap
import matplotlib.pyplot as plt

# ============================================================
# 1. Load data
# ============================================================

DATA_DIR = Path("cleaned data")

df = pd.read_csv(DATA_DIR / "FULLY MERGED.csv")


print("Loaded shape:", df.shape)
print(df.head())

df.columns

# ============================================================
# 2. Basic target cleanup
# ============================================================

# Keep only Paid / Denied rows
df = df[df["claim_status"].isin(["Paid", "Denied"])].copy()

# Encode target: Denied = 1, Paid = 0
df["target_denied"] = (df["claim_status"] == "Denied").astype(int)

print(df["claim_status"].value_counts())
print(df["target_denied"].value_counts(normalize=True))

print(df.isna().sum().sort_values(ascending=False))

# ============================================================
# 3. Feature engineering
# ============================================================

# Convert dates if they exist
date_cols = [
    "scheduled_date",
    "appointment_date",
    "submission_date",
    "dob",
    "registration_date"
]

for col in date_cols:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], errors="coerce")

# Age at claim/appointment
if "dob" in df.columns:
    if "submission_date" in df.columns:
        df["age_at_claim"] = (
            (df["submission_date"] - df["dob"]).dt.days / 365.25
        )
    elif "appointment_date" in df.columns:
        df["age_at_appointment"] = (
            (df["appointment_date"] - df["dob"]).dt.days / 365.25
        )

# Appointment timing features
if "appointment_date" in df.columns:
    df["appointment_month"] = df["appointment_date"].dt.month
    df["appointment_dayofweek"] = df["appointment_date"].dt.dayofweek

# Claim timing features known at submission
if "submission_date" in df.columns:
    df["submission_month"] = df["submission_date"].dt.month
    df["submission_dayofweek"] = df["submission_date"].dt.dayofweek

# ============================================================
# 4. Choose features and avoid leakage
# ============================================================

target_col = "target_denied"

# Columns to exclude because they are IDs, target, or leakage
exclude_cols = [
    # target / labels
    "claim_status",
    "target_denied",

    # identifiers, not meaningful predictors
    "claim_id",
    "appointment_id",
    "patient_id",
    # "provider_id",

    # raw dates already converted into features
    "scheduled_date",
    "appointment_date",
    "submission_date",
    "payment_date",
    "dob",
    "registration_date",

    # clear leakage: only known after adjudication/payment
    "payment_amount",
    "insurance_paid",
    "patient_paid",
    "amount_mismatch_flag",
    "date_logic_flag",

    # manual workflow / post-review leakage if present
    "task_id",
    "task_type",
    "created_date",
    "completed_date",
    "manual_minutes",
    "error_flag",
    "task_type_ambiguous_flag",
    "error_flag_missing_flag",
    "date_order_flag",
    "manual_minutes_invalid_flag",

    # location may be too granular/noisy, optional to exclude
    "postal_code",

    "patient_id",              # Identifier
    "first_name",              # No meaningful predictive value
    "last_name",               # No meaningful predictive value
    "status",                  # Constant ("Completed")
    "status_raw",              # Same information as status
    "future_no_show_flag",     # Constant (all 0)
    "claim_denied_final",      # Target leakage

    "patient_id_raw",
    "insurance_type",
    'patient_id_appt',
    'department_id_appt',

    # dept variables
    "department_id",
    "department_name",
    "location",
    "annual_budget",
    "base_wait_days",
    "manual_workload_multiplier",
    "claim_denial_risk",
    "lab_delay_risk"
]

available_exclude_cols = [c for c in exclude_cols if c in df.columns]

X = df.drop(columns=available_exclude_cols, errors="ignore")
y = df[target_col]

# Remove columns that are completely empty
X = X.dropna(axis=1, how="all")

print("Outcome:", target_col)
print("Feature matrix shape:", X.shape)

print("\nFeatures used:")
for col in X.columns:
    print("-", col)

print("\nExcluded columns:")
for col in available_exclude_cols:
    print("-", col)

# ============================================================
# 5. Preprocessing
# ============================================================

numeric_features = X.select_dtypes(include=["int64", "float64", "Int64"]).columns.tolist()
categorical_features = X.select_dtypes(include=["object", "bool", "category"]).columns.tolist()

numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

print("Numeric features:", numeric_features)
print("Categorical features:", categorical_features)

# ============================================================
# 6. Define models and grids
# ============================================================

scale_pos_weight = (y == 0).sum() / (y == 1).sum()
print(scale_pos_weight)

models = {
    "Logistic Regression": {
        "model": LogisticRegression(max_iter=2000, class_weight="balanced"),
        "params": {
            "model__C": [0.01, 0.1, 1, 10]
        }
    },

    "Random Forest": {
        "model": RandomForestClassifier(
            random_state=42,
            class_weight="balanced",
            n_jobs=-1
        ),
        "params": {
            "model__n_estimators": [50],
            "model__max_depth": [3, 5],
            "model__min_samples_leaf": [5]
        }
    },

    "Gradient Boosting": {
        "model": GradientBoostingClassifier(random_state=42),
        "params": {
            "model__n_estimators": [50],
            "model__learning_rate": [0.1],
            "model__max_depth": [3]
        }
    }
}

models["XGBoost"] = {
    "model": XGBClassifier(
        random_state=42,
        eval_metric="logloss",
        use_label_encoder=False,
        n_jobs=-1,
        scale_pos_weight=scale_pos_weight
    ),
    "params": {
        "model__n_estimators": [50],
        "model__max_depth": [3, 5],
        "model__learning_rate": [0.1]
    }
}

# Commented out IPython magic to ensure Python compatibility.
# %%time
# # ============================================================
# # 7. Nested cross-validation
# # ============================================================
# 
# outer_cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
# inner_cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
# 
# results = []
# best_models = {}
# 
# for model_name, config in models.items():
#     print(f"\nRunning nested CV for: {model_name}")
# 
#     fold_results = []
# 
#     for fold, (train_idx, test_idx) in enumerate(outer_cv.split(X, y), start=1):
#         X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
#         y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]
# 
#         pipe = Pipeline(steps=[
#             ("preprocess", preprocessor),
#             ("model", config["model"])
#         ])
# 
#         grid = GridSearchCV(
#             estimator=pipe,
#             param_grid=config["params"],
#             scoring="roc_auc",
#             cv=inner_cv,
#             n_jobs=-1
#         )
# 
#         grid.fit(X_train, y_train)
# 
#         best_model = grid.best_estimator_
#         y_prob = best_model.predict_proba(X_test)[:, 1]
#         threshold = 0.6
#         y_pred = (y_prob >= threshold).astype(int)
#         # y_pred = (y_prob >= 0.5).astype(int)
# 
#         fold_result = {
#             "model": model_name,
#             "fold": fold,
#             "auc": roc_auc_score(y_test, y_prob),
#             "accuracy": accuracy_score(y_test, y_pred),
#             "precision": precision_score(y_test, y_pred, zero_division=0),
#             "recall": recall_score(y_test, y_pred, zero_division=0),
#             "f1": f1_score(y_test, y_pred, zero_division=0),
#             "best_params": grid.best_params_
#         }
# 
#         fold_results.append(fold_result)
#         results.append(fold_result)
# 
#         print(
#             f" Fold {fold}: "
#             f"AUC={fold_result['auc']:.3f}, "
#             f"Acc={fold_result['accuracy']:.3f}, "
#             f"Recall={fold_result['recall']:.3f}"
#         )
# 
#     best_models[model_name] = fold_results
# 
# results_df = pd.DataFrame(results)
# results_df

# ============================================================
# 8. Summary performance table
# ============================================================

summary = (
    results_df
    .groupby("model")
    .agg(
        mean_auc=("auc", "mean"),
        sd_auc=("auc", "std"),
        mean_accuracy=("accuracy", "mean"),
        mean_precision=("precision", "mean"),
        mean_recall=("recall", "mean"),
        mean_f1=("f1", "mean")
    )
    .sort_values("mean_auc", ascending=False)
)

summary

# ============================================================
# 9. Fit final best model on all data
# ============================================================

best_model_name = summary.index[0]
print("Best model:", best_model_name)

best_config = models[best_model_name]

final_pipe = Pipeline(steps=[
    ("preprocess", preprocessor),
    ("model", best_config["model"])
])

final_grid = GridSearchCV(
    estimator=final_pipe,
    param_grid=best_config["params"],
    scoring="roc_auc",
    cv=inner_cv,
    n_jobs=-1
)

final_grid.fit(X, y)

final_model = final_grid.best_estimator_

print("Best final parameters:")
print(final_grid.best_params_)

# ============================================================
# 10. Risk score function A
# ============================================================

def risk_category(prob_denied):
    if prob_denied < 0.30:
        return "Low Risk"
    elif prob_denied < 0.70:
        return "Medium Risk"
    else:
        return "High Risk"

df["predicted_denial_probability"] = final_model.predict_proba(X)[:, 1]
df["risk_category"] = df["predicted_denial_probability"].apply(risk_category)

df[["claim_status", "predicted_denial_probability", "risk_category"]].head(10)

# ============================================================
# 10. Risk score function B
# ============================================================

df["predicted_denial_probability"] = final_model.predict_proba(X)[:, 1]

low_cutoff = df["predicted_denial_probability"].quantile(0.80)
high_cutoff = df["predicted_denial_probability"].quantile(0.95)

print("Medium cutoff:", low_cutoff)
print("High cutoff:", high_cutoff)

def risk_category(prob_denied):
    if prob_denied < low_cutoff:
        return "Low Risk"
    elif prob_denied < high_cutoff:
        return "Medium Risk"
    else:
        return "High Risk"

df["risk_category"] = df["predicted_denial_probability"].apply(risk_category)

df[["claim_status", "predicted_denial_probability", "risk_category"]].head(30)

# ============================================================
# 11. SHAP interpretation
# ============================================================

# Transform X using fitted preprocessing
X_transformed = final_model.named_steps["preprocess"].transform(X)

feature_names = final_model.named_steps["preprocess"].get_feature_names_out()

# Convert sparse matrix to dense if needed
if hasattr(X_transformed, "toarray"):
    X_transformed = X_transformed.toarray()

X_shap = pd.DataFrame(X_transformed, columns=feature_names)

# Use a sample for speed
shap_sample = X_shap.sample(
    n=min(500, len(X_shap)),
    random_state=42
)

model_only = final_model.named_steps["model"]

explainer = shap.Explainer(model_only, shap_sample)
shap_values = explainer(shap_sample)

shap.plots.beeswarm(shap_values, max_display=20)

# ============================================================
# 12. Save model outputs
# ============================================================

summary.to_csv("model_performance_nested_cv.csv")
results_df.to_csv("model_performance_by_fold.csv", index=False)

df.to_csv("claims_with_predicted_risk.csv", index=False)

print("Saved:")
print("- model_performance_nested_cv.csv")
print("- model_performance_by_fold.csv")
print("- claims_with_predicted_risk.csv")

